# select  hour(DATETIME) as HOUR
#         , count(*) as COUNT
# from    ANIMAL_OUTS 
# where   hour(DATETIME) between 0 and 23
# group   by hour(DATETIME)
# order   by 1

WITH RECURSIVE Y AS (
SELECT ROW_NUMBER() OVER(ORDER BY DATETIME)-1 AS HOUR
FROM ANIMAL_OUTS 
LIMIT 24 )

SELECT HOUR , COUNT(ANIMAL_ID) AS Count
FROM Y
LEFT JOIN ANIMAL_OUTS
ON DATE_FORMAT(DATETIME,"%H") = Y.HOUR
GROUP BY HOUR
ORDER BY HOUR